# Path to rules file which contains Sigma-style rules that define patterns to 
# detect suspicious log entries and assign risk scores based on attributes like 
# IP, URI, status, referrer, user_agent, etc. 
rules_path: rules.yaml

# Path to a file listing known webshell names. This file helps calculate risk 
# scores for log entries by identifying suspicious URI paths that match known 
# webshell patterns (e.g., 'backdoor.php' and '1.php').
webshell_path: shells.txt

# List of file extensions to exclude from default output. These are typically 
# static or non-suspicious file types (e.g., images, fonts, stylesheets) that
# are filtered to focus analysis on potentially risky log entries.
ignore_extensions:
  - .js
  - .gif
  - .css
  - .woff
  - .woff2
  - .ttf
  - .svg
  - .ico
  - .map
  - .eot
  - .jpg
  - .jpeg
  - .png
  - .bmp
  - .webp

# Authorised scanning tool IP addresses to ignore. Supports cidr notation.  
ignore_ip:
  # Qualys
  - 10.10.10.10

# Configuration for calculating risk scores based on URI paths. Defines 
# sensitive paths and file extensions that could indicate potential issues. 
# Used by risk scoring algorithm for URI paths. Lightly weighted. 
uri_risk:
  # Commonly targeted or sensitive paths (e.g., admin or config endpoints).
  sensitive_paths: 
    - /admin
    - /login
    - /config
    - /setup
    - /upload
  # File extensions associated with risky files (e.g., scripts or database dumps).
  sensitive_extensions:
    - .exe
    - .sql
    - .cgi
    - .pl

# Email settings
# email:
#   sender: terry.uppercut@gmail.com
#   smtp_server: smtp.terry.com
#   smtp_port: 25
#   body: "Please find attached results generated by WebLogTriage."


# Defines signatures to identify malicious website scanning tools 
# by matching specific URIs in log entries within a defined time window.
# User Agent support to be added in the future. 
tool_signatures:

  # DirSearch - https://github.com/maurosoria/dirsearch
  - tool: DS01
    name: DirSearch
    description: DirSearch using default dictionary (dicc.txt). 
    # List of URIs or filenames commonly requested by the tool.
    # These are matched against the request URI in log entries. All filenames
    # must be matched within the specified time window for a positive identification. 
    keyword:
      - /.access
      - .bak_0.log
      - .chef/config.rb
      - .isort.cfg
      - .spacemacs
      - /~xfs
    # Time window (in seconds) to group log entries for detection.
    # Example: 7200 seconds (2 hours) means multiple matches within 2 hours 
    # are flagged as single tool activity.
    time_window: 7200